#!/bin/sh
# 装 skillpm。内网机器外网慢，所以默认**完全不碰 PyPI**。
#
#   ./scripts/install.sh              自动挑一种能用的装法
#   ./scripts/install.sh --pip        强制用 pip
#   ./scripts/install.sh --launcher   强制只做启动器（最快，零网络）
#   PREFIX=/some/bin ./scripts/install.sh   指定装到哪个目录
set -e
DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MODE=${1:-auto}

# 重复运行 = 更新：先把源码拉到最新，再重新链接。
# 这样「装」和「更新」就是同一条命令，不用记两套。
sync_source() {
  [ -d "$DIR/.git" ] || return 0
  command -v git >/dev/null 2>&1 || return 0
  if [ -n "$(git -C "$DIR" status --porcelain 2>/dev/null)" ]; then
    echo "（源码目录有未提交的改动，跳过 git pull，用当前版本）"
    return 0
  fi
  before=$(git -C "$DIR" rev-parse --short HEAD 2>/dev/null || echo "")
  echo "拉取最新源码…"
  git -C "$DIR" pull --ff-only >/dev/null 2>&1 || { echo "  git pull 没成功，用当前版本继续"; return 0; }
  after=$(git -C "$DIR" rev-parse --short HEAD 2>/dev/null || echo "")
  [ "$before" != "$after" ] && echo "  源码已更新：$before → $after" || echo "  已是最新"
}
sync_source

PY=$(command -v python3 || command -v python) || {
  echo "没找到 Python 3，先装一个（3.8 以上）" >&2; exit 1; }

on_path() {
  case ":$PATH:" in *":$1:"*) return 0 ;; *) return 1 ;; esac
}

# 挑一个「已经在 PATH 里、而且能写」的目录，省得装完还要你改配置
pick_bin() {
  [ -n "$PREFIX" ] && { echo "$PREFIX"; return; }
  for d in "$HOME/.local/bin" /usr/local/bin "$HOME/bin"; do
    if on_path "$d" && { [ -w "$d" ] || mkdir -p "$d" 2>/dev/null; }; then
      echo "$d"; return
    fi
  done
  echo "$HOME/.local/bin"        # 都不在 PATH，装这儿再引导加 PATH
}

# 找用户的 shell 配置文件
rc_file() {
  case "${SHELL##*/}" in
    zsh)  echo "$HOME/.zshrc" ;;
    bash) [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" ;;
    fish) echo "$HOME/.config/fish/config.fish" ;;
    *)    echo "$HOME/.profile" ;;
  esac
}

offer_path() {
  BIN=$1
  on_path "$BIN" && return 0
  RC=$(rc_file)
  LINE="export PATH=\"$BIN:\$PATH\""
  [ "${SHELL##*/}" = "fish" ] && LINE="fish_add_path $BIN"
  if [ -f "$RC" ] && grep -Fq "$BIN" "$RC" 2>/dev/null; then
    echo "（$RC 里已经有这个目录了，新开终端就生效）"
    return 0
  fi
  printf "%s 不在 PATH 里。要我加进 %s 吗？[Y/n] " "$BIN" "$RC"
  read -r ans </dev/tty || ans=n
  case "$ans" in
    ""|y|Y|yes|YES)
      mkdir -p "$(dirname "$RC")"
      printf '\n# skillpm\n%s\n' "$LINE" >> "$RC"
      echo "已加进 $RC —— 新开一个终端，或者先跑：$LINE"
      ;;
    *)
      echo "那你自己加这行：$LINE"
      ;;
  esac
}

install_with_pip() {
  # --no-build-isolation：用本机已有的 setuptools 打包，不去 PyPI 下东西。
  # 内网机器上这一条是关键，否则 pip 会卡在「Collecting setuptools」几分钟。
  echo "用 pip 安装（不走 PyPI）…"
  "$PY" -m pip install --no-build-isolation --user "$DIR" 2>&1 | grep -viE "^\s*(DEPRECATION|WARNING: You are using pip)" || true
  BIN=$("$PY" -c 'import site,os;print(os.path.join(site.USER_BASE,"bin"))')
  echo "装好了：$BIN/skillpm"
  offer_path "$BIN"
  echo "验证：skillpm -v"
}

make_launcher() {
  TARGET=$(pick_bin)
  mkdir -p "$TARGET"
  cat > "$TARGET/skillpm" <<WRAP
#!/bin/sh
# generated by skillpm/scripts/install.sh；源码在 $DIR
exec "$PY" -c "import sys;sys.path.insert(0,'$DIR/src');from skillpm.cli import main;sys.exit(main())" "\$@"
WRAP
  chmod +x "$TARGET/skillpm"
  # 记下来，卸载时按这个清
  mkdir -p "$HOME/.skillpm"
  printf '%s\n' "$TARGET/skillpm" > "$HOME/.skillpm/.installed-at"
  echo "装好了：$TARGET/skillpm"
  offer_path "$TARGET"
  echo "验证：skillpm -v"
  echo "以后升级：直接敲 skillpm self-update（在哪个目录都行）"
}

case "$MODE" in
  --launcher) make_launcher ;;
  --pip)      install_with_pip ;;
  *)
    # 启动器更干净：升级只要 git pull，卸载只要删一个文件
    make_launcher
    ;;
esac
